- hosts: node
  remote_user: root
  tasks:
    - name: 停止程序
      service:
        name: '{{ item.name }}'
        state: stopped
      with_items:
        - { name: 'kubelet' }
        - { name: 'kube-proxy' }
        - { name: 'containerd' }

    - name: 删除相关目录
      file:
        path: '{{ item.path }}'
        state: absent
      with_items:
        - { path: '/var/log/kubernetes' }
        - { path: '/etc/kubernetes' }
        - { path: '/var/lib/kubelet' }
        - { path: '/etc/containerd' }
        - { path: '/etc/cni/net.d' }
        - { path: '/opt/cni/bin' }
        - { path: '/var/lib/cni' }

    - name: 删除启动项文件
      file:
        path: /usr/lib/systemd/system/{{ item.service }}.service
        state: absent
      with_items:
        - { service: 'kubelet' }
        - { service: 'kube-proxy' }
        - { service: 'containerd' }

    - name: 删除二进制文件
      file:
        path: /usr/bin/{{ item.bin }}
        state: absent
      with_items:
        - { bin: 'kubelet' }
        - { bin: 'kube-proxy' }
        - { bin: 'ctr' }
        - { bin: 'containerd' }
        - { bin: 'containerd-shim' }
        - { bin: 'containerd-shim-runc-v1' }
        - { bin: 'containerd-shim-runc-v2' }

    - name: 删除证书文件
      file:
        path: /etc/ssl/kubernetes
        state: absent

    - name: 删除 网桥
      shell: ip link del kube-ipvs0 

    - name: 清理 iptables 规则
      shell: iptables -F && iptables -X && iptables -Z


- hosts: master
  remote_user: root
  tasks:
    - name: 停止程序
      service:
        name: '{{ item.name }}'
        state: stopped
      with_items:
        - { name: 'haproxy' }
        - { name: 'keepalived' }
        - { name: 'kube-scheduler' }
        - { name: 'kube-controller-manager' }
        - { name: 'kube-apiserver' }

    - name: 删除相关目录
      file:
        path: '{{ item.path }}'
        state: absent
      with_items:
        - { path: '/etc/haproxy' }
        - { path: '/etc/keepalived' }
        - { path: '/var/log/kubernetes' }
        - { path: '/etc/kubernetes' }
        - { path: '/root/.kube' }


    - name: 删除启动项文件
      file:
        path: /usr/lib/systemd/system/{{ item.service }}.service
        state: absent
      with_items:
        - { service: 'haproxy' }
        - { service: 'keepalived' }
        - { service: 'kube-scheduler' }
        - { service: 'kube-controller-manager' }
        - { service: 'kube-apiserver' }

    - name: 删除二进制文件
      file:
        path: /usr/local/sbin/{{ item.bin }}
        state: absent
      with_items:
        - { bin: 'haproxy' }
        - { bin: 'keepalived' }
    - name: 删除二进制文件
      file:
        path: /usr/bin/{{ item.bin }}
        state: absent
      with_items:
        - { bin: 'kube-scheduler' }
        - { bin: 'kube-controller-manager' }
        - { bin: 'kube-apiserver' }
        - { bin: 'kubectl' }
        - { bin: 'kubeadm' }

    - name: 删除用户
      shell: userdel haproxy

    - name: 删除证书文件
      file:
        path: /etc/ssl/kubernetes
        state: absent

    - name: 清理 iptables 规则
      shell: iptables -F && iptables -X && iptables -Z

- hosts: etcd
  remote_user: root
  tasks:
    - name: 停止程序
      service:
        name: etcd
        state: stopped

    - name: 删除相关目录
      file:
        path: '{{ item.path }}'
        state: absent
      with_items:
        - { path: '/etc/etcd' }
        - { path: '/var/lib/etcd' }

    - name: 删除启动项文件
      file:
        path: /usr/lib/systemd/system/etcd.service
        state: absent

    - name: 删除二进制文件
      file:
        path: /usr/bin/{{ item.bin }}
        state: absent
      with_items:
        - { bin: 'etcd' }
        - { bin: 'etcdctl' }

    - name: 删除证书文件
      file:
        path: /etc/ssl/etcd
        state: absent
